apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epinexus

resources:
  - namespace.yaml
  - secrets.yaml
  - storage.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - frontend.yaml
  - worker.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"
